apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rest-simulator
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: rest-simulator
spec:
  selector:
    matchLabels:
      app: rest-simulator
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
  namespaceSelector:
    any: true
